# Homework 3: Numbers

**1**. Vectorize the following code using `numpy`.

Part 1

In [2]:
[i**2 for i in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [4]:
import numpy as np

In [7]:
np.arange(10)**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

Part 2

In [42]:
xs = range(1, 11)
ys = range(2, 12)
s = 0
for i in range(len(xs)):
    s += xs[i]*ys[i]
s

440

In [48]:
xs = np.array(xs)
ys = np.array(ys)
xs @ ys

440

Part 3

In [49]:
s = 0
for i in range(1, 11):
    for j in range(2, 12):
        s += i*j
s

3575

In [50]:
i = np.arange(1, 11).reshape(-1,1)
j = np.arange(2, 12).reshape(-1,1)
np.sum(i @ j.T)

3575

Part 4

In [52]:
m = 3
n = 2
alpha = np.random.rand(1)
betas = np.random.rand(n,1)
xs = np.random.rand(m,n)

ys = np.zeros((m,1))
for i in range(m):
    ys[i] = alpha
    for j in range(n):
        ys[i] += betas[j] * xs[i,j]
ys

array([[1.94579697],
       [1.060151  ],
       [1.79745268]])

In [54]:
ys = alpha + xs @ betas
ys

array([[1.94579697],
       [1.060151  ],
       [1.79745268]])