# Vectors and matrices

This suppplements the notes at https://people.duke.edu/~ccc14/sta-663-2018/notebooks/S03_Numpy_Annotated.html to go over more challenging concepts.

In [180]:
import numpy as np

## Vectors

In mathematics, the default is to use a column vector $x$. To denote a row vector, we use $x^T$.

In [181]:
x = np.arange(1, 5).reshape(-1,1)
x

array([[1],
       [2],
       [3],
       [4]])

In [182]:
y = np.arange(4, 0, -1).reshape(-1,1)
y

array([[4],
       [3],
       [2],
       [1]])

## Simple operations on vectors

### Element-wise operations

In [183]:
x + y

array([[5],
       [5],
       [5],
       [5]])

In [184]:
x * y

array([[4],
       [6],
       [6],
       [4]])

In [185]:
x / y

array([[0.25      ],
       [0.66666667],
       [1.5       ],
       [4.        ]])

In [186]:
x ** y

array([[1],
       [8],
       [9],
       [4]])

### Universal functions

In [187]:
x**2

array([[ 1],
       [ 4],
       [ 9],
       [16]])

In [188]:
np.log(x)

array([[0.        ],
       [0.69314718],
       [1.09861229],
       [1.38629436]])

In [189]:
np.cos(x)

array([[ 0.54030231],
       [-0.41614684],
       [-0.9899925 ],
       [-0.65364362]])

### Vector reductions

In [190]:
x.sum()

10

In [191]:
x.mean()

2.5

In [192]:
x.max()

4

### Transpose

In [193]:
x.transpose()

array([[1, 2, 3, 4]])

In [194]:
x.T

array([[1, 2, 3, 4]])

## Vector multiplication


Standard inner or dot proudct

In [195]:
x.T.dot(x)

array([[30]])

In [196]:
x.T @ x

array([[30]])

If you just want the scalar result

In [197]:
(x.T @ x).item()

30

Contrast with the outer product

In [198]:
x @ x.T

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [199]:
np.squeeze(x.T @ x)

array(30)

## Matrices

### Basically 2D arrays

In [200]:
A = np.arange(1, 13).reshape(3,4)

In [201]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [202]:
A.shape

(3, 4)

### Most things work just like for vectors

In [203]:
A + A

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [204]:
A**2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [205]:
np.log(A)

array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527, 2.48490665]])

In [206]:
A.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

## Matrix multiplication

In [207]:
A @ A.T

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

In [208]:
A.T @ A

array([[107, 122, 137, 152],
       [122, 140, 158, 176],
       [137, 158, 179, 200],
       [152, 176, 200, 224]])

### Matrix vector multiplication

Withc column vectors

In [209]:
A @ x

array([[ 30],
       [ 70],
       [110]])

With row vectors

In [210]:
x.T @ A.T

array([[ 30,  70, 110]])

## Extrracting vectors from matrices

In [211]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Get column vectors

In [212]:
c0 = np.array([1,0,0,0]).reshape(-1, 1)
c0

array([[1],
       [0],
       [0],
       [0]])

In [213]:
c2 = np.array([0,0,1,0]).reshape(-1, 1)
c2

array([[0],
       [0],
       [1],
       [0]])

In [214]:
A @ c0

array([[1],
       [5],
       [9]])

In [215]:
A @ c2

array([[ 3],
       [ 7],
       [11]])

### So multiplying a matrix with a column vector gives a weighted sum of the marix columns

In [216]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [217]:
x

array([[1],
       [2],
       [3],
       [4]])

In [218]:
A @ x

array([[ 30],
       [ 70],
       [110]])

Exploain how we got the result above.

Similar things can be done with rows.

In [219]:
r2 = np.array([0,0,1])
r2

array([0, 0, 1])

In [220]:
r2 @ A

array([ 9, 10, 11, 12])

Multiplying two matrices can be seen as geenrating the weighted sums column by column (or row by row)

In [221]:
B = np.array([
    [1,2,3],
    [1,2,3],
    [1,2,3],
    [1,2,3]
])
B

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [222]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Column interpreation

In [223]:
A @ B[:, 0].reshape(-1,1)

array([[10],
       [26],
       [42]])

In [224]:
A @ B[:, 1].reshape(-1,1)

array([[20],
       [52],
       [84]])

In [225]:
A @ B[:, 2].reshape(-1,1)

array([[ 30],
       [ 78],
       [126]])

In [226]:
A @ B

array([[ 10,  20,  30],
       [ 26,  52,  78],
       [ 42,  84, 126]])

Row interpretation

In [227]:
A[0,:]

array([1, 2, 3, 4])

In [228]:
B

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [229]:
A[0,:] @ B

array([10, 20, 30])

How did we get this result?

In [230]:
A[1, :]

array([5, 6, 7, 8])

In [231]:
A[1,:] @ B

array([26, 52, 78])

In [232]:
A[2,:] @ B

array([ 42,  84, 126])

In [233]:
A @ B

array([[ 10,  20,  30],
       [ 26,  52,  78],
       [ 42,  84, 126]])

### Permutations can be seen as rearranging columns

In [234]:
A.shape

(3, 4)

In [235]:
I = np.eye(A.shape[1], dtype='int')
I

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [236]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [237]:
A @ I

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

We can interpret the post-(or rihgt-)multiplicatin of A with the identify matrix like so:
    
- The 1st column of I takes 1 of 1st column of A and 0 of everything else
- The 2nd columnn of I takes 1 of 2nd column of A and 0 of everything else
- The 3rd column of I takes 1 of 3rd column of A and 0 of everything else
- The 4th columnn of I takes 1 of 4th column of A and 0 of everything else

In [238]:
I1 = I[:, [2,0,3,1]]
I1

array([[0, 1, 0, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 0, 1, 0]])

In [239]:
A @ I1

array([[ 3,  1,  4,  2],
       [ 7,  5,  8,  6],
       [11,  9, 12, 10]])

In [240]:
A[:, [2,0,3,1]]

array([[ 3,  1,  4,  2],
       [ 7,  5,  8,  6],
       [11,  9, 12, 10]])

Pre-multiplication by a permuted identity martrix does the same things to the *rows* of A. (not shown)

## Broadcasting

A scalar can be *promoted* or *broadcast* to be a vector or matrix

In [241]:
x

array([[1],
       [2],
       [3],
       [4]])

In [242]:
x + 1

array([[2],
       [3],
       [4],
       [5]])

In [243]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [244]:
A + 1

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

A vecotr can be promoted to a matrix if the *shape* is right

In [245]:
u = np.ones(3, dtype='int').reshape(-1,1)
u

array([[1],
       [1],
       [1]])

In [246]:
A.shape

(3, 4)

In [247]:
u.shape

(3, 1)

In [248]:
A + u

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [249]:
x.T.shape

(1, 4)

In [250]:
A.shape

(3, 4)

In [251]:
A + x.T

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12],
       [10, 12, 14, 16]])

### Broadcasting rules

- Look at the sahpes of the two arrays from right to left
- If the numbers are the same, it is ok
- If one number is 1, it will be promoted to the size of the other
- If one number is missing, it wil be promoted to the sie of the other
- Everything else will be an error

In [252]:
A.shape, u.shape

((3, 4), (3, 1))

In [253]:
A + u

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

Promotions means `numpy` does something like this under the hood.

In [254]:
u1 = u @ np.ones((1,4), dtype='int')
u1

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [255]:
A.shape, u1.shape

((3, 4), (3, 4))

In [256]:
A + u1

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

### To enable broadcasting,  you can add *dummy* dimensions

In [257]:
A.shape

(3, 4)

In [258]:
A[:, None].shape

(3, 1, 4)

In [259]:
A[:, None]

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

In [260]:
A[:, :, None].shape

(3, 4, 1)

Some people prefer `np.newaxis` to `None` — they are identical

In [261]:
A[:, np.newaxis, :].shape

(3, 1, 4)

In [262]:
A[np.newaxis, ...].shape

(1, 3, 4)

In [263]:
x

array([[1],
       [2],
       [3],
       [4]])

In [264]:
x.shape, A[:, :, None].shape

((4, 1), (3, 4, 1))

In [265]:
A[:, :, None] + x

array([[[ 2],
        [ 4],
        [ 6],
        [ 8]],

       [[ 6],
        [ 8],
        [10],
        [12]],

       [[10],
        [12],
        [14],
        [16]]])

## Broadcasting example

In [266]:
w = np.arange(1, 13)

In [267]:
w.shape

(12,)

In [268]:
w[None, :].shape

(1, 12)

Note that w[None, :] converts the 1D array `w` into a row vector.

In [269]:
w[None, :]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [270]:
w[:, None].shape

(12, 1)

Note that w[:, None] converts the 1D array `w` into a row vector.

In [271]:
w[:, None]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

What does this do?

In [272]:
w[:, None] * w[None, :]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80,  88,  96],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90,  99, 108],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120],
       [ 11,  22,  33,  44,  55,  66,  77,  88,  99, 110, 121, 132],
       [ 12,  24,  36,  48,  60,  72,  84,  96, 108, 120, 132, 144]])

How does this work?

In [273]:
w[None, :].shape, w[:, None].shape

((1, 12), (12, 1))

We work from right to left in the shapes — so the first numbers to match are 12 and 1. Broadcasting thus promotes the second array to be (12, 12). Now we need to match 1 to 12, so the first array is also promoted to be (12, 12).

Now the first array looks like this

In [274]:
w

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [275]:
w1 = np.tile(w[None, :], (12, 1))
w1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

And the second array looks like this

In [276]:
w2 = np.tile(w[:, None], (1, 12))
w2

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4],
       [ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5],
       [ 6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6],
       [ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7],
       [ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8],
       [ 9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11],
       [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12]])

And element-wsie multiplication takes care of the rest.

In [277]:
w1 * w2

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80,  88,  96],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90,  99, 108],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120],
       [ 11,  22,  33,  44,  55,  66,  77,  88,  99, 110, 121, 132],
       [ 12,  24,  36,  48,  60,  72,  84,  96, 108, 120, 132, 144]])

## Vectorizing loops

Learn to recognise how to convert loops into vectorized `numpy` operations and vice versa.

### Universal functions

In [278]:
x

array([[1],
       [2],
       [3],
       [4]])

In [279]:
m, n = x.shape
s = x.copy()
for i in range(m):
    s[i] = x[i]**2
s

array([[ 1],
       [ 4],
       [ 9],
       [16]])

Can just be written as

In [280]:
s = x**2
s

array([[ 1],
       [ 4],
       [ 9],
       [16]])

### Scalar product

In [281]:
x

array([[1],
       [2],
       [3],
       [4]])

In [282]:
y

array([[4],
       [3],
       [2],
       [1]])

Vectorized form

In [283]:
x.T @ y

array([[20]])

Unrolled version

In [284]:
s = 0
for i in range(m):
     s += x[i] * y[i]
s

array([20])

### Matrix vector proudct

In [285]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [286]:
x

array([[1],
       [2],
       [3],
       [4]])

Vectroized form

In [287]:
A @ x

array([[ 30],
       [ 70],
       [110]])

Unrolled version

In [288]:
s = np.zeros(A.shape[0]).reshape(-1, 1)
m, n = A.shape
for i in range(m):
    for j in range(n):
        s[i] += A[i, j] * x[j]
s

array([[ 30.],
       [ 70.],
       [110.]])

## Matrix manipulation

In [289]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [290]:
m, n = A.shape

#### Sum across rows to get column sums

Pre-multiply with row vector of ones.

In [291]:
np.ones((m,1)).T @ A

array([[15., 18., 21., 24.]])

Check

In [292]:
A.sum(axis=0)

array([15, 18, 21, 24])

#### Sum across columns to get row sums

Post-multiply wiht column vector of ones.

In [293]:
A @ np.ones((n, 1))

array([[10.],
       [26.],
       [42.]])

Check

In [294]:
A.sum(axis=1)

array([10, 26, 42])

#### Global sum 

In [295]:
np.ones((m,1)).T @ A @ np.ones((n, 1))

array([[78.]])

Check

In [296]:
A.sum()

78

#### Global mean

In [297]:
np.ones((m,1)).T @ A @ np.ones((n, 1))/(m * n)

array([[6.5]])

Check

In [298]:
A.mean()

6.5

#### Scaling rows

In [299]:
np.diag([1,2,3]) @ A

array([[ 1,  2,  3,  4],
       [10, 12, 14, 16],
       [27, 30, 33, 36]])

#### Scaling columns

In [300]:
A @ np.diag([1,2,3,4])

array([[ 1,  4,  9, 16],
       [ 5, 12, 21, 32],
       [ 9, 20, 33, 48]])

#### Standardization

$\text{Standardize}(X) = (X - \mathbb{1}_N \mu^T)\text{diag}(\sigma)^{-1}$

In [301]:
μ = A.mean(axis=0).reshape(-1,1)
μ

array([[5.],
       [6.],
       [7.],
       [8.]])

In [302]:
σ = A.std(axis=0)
σ

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [303]:
(A - np.ones((m, 1)) @ μ.T) @ np.diag(1/σ)

array([[-1.22474487, -1.22474487, -1.22474487, -1.22474487],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.22474487,  1.22474487,  1.22474487,  1.22474487]])

Check — broadcasting makes this easy.

The matrix version shows how to write the operation mathematically using matrix notation

In [304]:
(A - A.mean(axis=0))/(A.std(axis=0))

array([[-1.22474487, -1.22474487, -1.22474487, -1.22474487],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.22474487,  1.22474487,  1.22474487,  1.22474487]])

### Sum of squares matrix

In [305]:
A.T @ A

array([[107, 122, 137, 152],
       [122, 140, 158, 176],
       [137, 158, 179, 200],
       [152, 176, 200, 224]])

### Scatter matrix

The scatter matrix is the sum of squares matrix after column centering.

Mathematically, it is expressed as scaling by a centering matrix, but in numpy is easier to do via multiplicaiotn of centered martrces.

Defining and using centering matrix C

In [306]:
C = np.eye(m) - 1/m * np.ones((m,1)) @ np.ones((m,1)).T
C

array([[ 0.66666667, -0.33333333, -0.33333333],
       [-0.33333333,  0.66666667, -0.33333333],
       [-0.33333333, -0.33333333,  0.66666667]])

In [307]:
A.T @ C @ A

array([[32., 32., 32., 32.],
       [32., 32., 32., 32.],
       [32., 32., 32., 32.],
       [32., 32., 32., 32.]])

Direct solution

In [308]:
B = A - A.mean(axis=0)
B.T @ B

array([[32., 32., 32., 32.],
       [32., 32., 32., 32.],
       [32., 32., 32., 32.],
       [32., 32., 32., 32.]])

## Gram mattix

Matrix of inner products.

In [309]:
A @ A.T

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

### Distance matrix

The matrix euqation to calculate pairwise distances between row vectors in two matrices $A$ and $B$ is given by

$$
D = \hat{a}\mathbb{1}_{n_b}^{T} - 2AB + \mathbb{1}_{n_a}\hat{b}^T
$$

where $\hat{a} = \text{diag}(AA^T)$ ad $\hat{b} = \text{diag}(BB^T)$ are vectors whose elementer are the squared norms of the row vectors of $A$ and $B$ respectively.

In [310]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [311]:
B = np.arange(0, 16).reshape(-1, 4)
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [312]:
n, p = B.shape

In [313]:
â = np.diag(A @ A.T).reshape(-1,1)
â

array([[ 30],
       [174],
       [446]])

In [314]:
b̂ = np.diag(B @ B.T).reshape(-1,1)
b̂

array([[ 14],
       [126],
       [366],
       [734]])

In [315]:
np.sqrt(â @ np.ones((n,1)).T  - 2*A@B.T + np.ones((m,1))@b̂.T)

array([[ 2.,  6., 14., 22.],
       [10.,  2.,  6., 14.],
       [18., 10.,  2.,  6.]])

Check

In [316]:
from scipy.spatial.distance import cdist

In [317]:
cdist(A, B)

array([[ 2.,  6., 14., 22.],
       [10.,  2.,  6., 14.],
       [18., 10.,  2.,  6.]])